export interface Song {
  id: string;
  title: string;
  album: string;
  year: number;
  rank: number | null; // null means unranked (in the pool)
  comment: string;
  elo?: number; // Elo rating for Battle mode
  matchCount?: number; // Number of times compared
  audioUrl?: string; // Optional real audio URL
}

export const initialSongs: Song[] = [
  {
    id: "1",
    title: "雅俗共赏",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/1.mp3",
  },
  {
    id: "2",
    title: "庐州月",
    album: "《寻雾启示》",
    year: 2010,
    rank: null,
    comment: "",
    audioUrl: "/songs/2.mp3",
  },
  {
    id: "3",
    title: "有何不可",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/3.mp3",
  },
  {
    id: "4",
    title: "清明雨上",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/4.mp3",
  },
  {
    id: "5",
    title: "灰色头像",
    album: "《寻雾启示》",
    year: 2010,
    rank: null,
    comment: "",
    audioUrl: "/songs/5.mp3",
  },
  {
    id: "6",
    title: "山水之间",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/6.mp3",
  },
  {
    id: "7",
    title: "千百度",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/7.mp3",
  },
  {
    id: "8",
    title: "惊鸿一面",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/8.mp3",
  },
  {
    id: "9",
    title: "最佳歌手",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/9.mp3",
  },
  {
    id: "10",
    title: "城府",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/10.mp3",
  },
  {
    id: "11",
    title: "叹服",
    album: "《寻雾启示》",
    year: 2010,
    rank: null,
    comment: "",
    audioUrl: "/songs/11.mp3",
  },
  {
    id: "12",
    title: "乌鸦",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/12.mp3",
  },
  {
    id: "13",
    title: "想象之中",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/13.mp3",
  },
  {
    id: "14",
    title: "幻听",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/14.mp3",
  },
  {
    id: "15",
    title: "老古董",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/15.mp3",
  },
  {
    id: "16",
    title: "素颜",
    album: "单曲",
    year: 2010,
    rank: null,
    comment: "",
    audioUrl: "/songs/16.mp3",
  },
  {
    id: "17",
    title: "半城烟沙",
    album: "单曲",
    year: 2010,
    rank: null,
    comment: "",
    audioUrl: "/songs/17.mp3",
  },
  {
    id: "18",
    title: "断桥残雪",
    album: "单曲",
    year: 2007,
    rank: null,
    comment: "",
    audioUrl: "/songs/18.mp3",
  },
  {
    id: "19",
    title: "摄影艺术",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/19.mp3",
  },
  {
    id: "20",
    title: "大千世界",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/20.mp3",
  },
  {
    id: "21",
    title: "多余的解释",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/21.mp3",
  },
  {
    id: "22",
    title: "如果当时",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/22.mp3",
  },
  {
    id: "23",
    title: "星座书上",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/23.mp3",
  },
  {
    id: "24",
    title: "红尘沙画",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/24.mp3",
  },
  {
    id: "25",
    title: "单人旅途",
    album: "《寻雾启示》",
    year: 2010,
    rank: null,
    comment: "",
    audioUrl: "/songs/25.mp3",
  },
  {
    id: "26",
    title: "白马非马",
    album: "《寻雾启示》",
    year: 2010,
    rank: null,
    comment: "",
    audioUrl: "/songs/26.mp3",
  },
  {
    id: "27",
    title: "双人旁",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/27.mp3",
  },
  {
    id: "28",
    title: "降温",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/28.mp3",
  },
  {
    id: "29",
    title: "微博控",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/29.mp3",
  },
  {
    id: "30",
    title: "敬酒不吃",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/30.mp3",
  },
  {
    id: "31",
    title: "温差",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/31.mp3",
  },
  {
    id: "32",
    title: "胡萝卜须",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/32.mp3",
  },
  {
    id: "33",
    title: "闺蜜",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/33.mp3",
  },
  {
    id: "34",
    title: "弹指一挥间",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/34.mp3",
  },
  {
    id: "35",
    title: "等到烟火清凉",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/35.mp3",
  },
  {
    id: "36",
    title: "平行宇宙",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/36.mp3",
  },
  {
    id: "37",
    title: "清明",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/37.mp3",
  },
  {
    id: "38",
    title: "如约而至",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/38.mp3",
  },
  {
    id: "39",
    title: "艺术家们",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/39.mp3",
  },
  {
    id: "40",
    title: "科幻小说",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/40.mp3",
  },
  {
    id: "41",
    title: "冰柜",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/41.mp3",
  },
  {
    id: "42",
    title: "超市",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/42.mp3",
  },
  {
    id: "43",
    title: "玫瑰花的葬礼",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/43.mp3",
  },
  {
    id: "44",
    title: "南山忆",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/44.mp3",
  },
  {
    id: "45",
    title: "浅唱",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/45.mp",
  },
  {
    id: "46",
    title: "你若成风",
    album: "早期单曲",
    year: 2007,
    rank: null,
    comment: "",
    audioUrl: "/songs/46.mp3",
  },
  {
    id: "47",
    title: "雪花谣",
    album: "早期单曲",
    year: 2007,
    rank: null,
    comment: "",
    audioUrl: "/songs/47.mp3",
  },
  {
    id: "48",
    title: "飞驰于沙场",
    album: "近期单曲",
    year: 2024,
    rank: null,
    comment: "",
    audioUrl: "/songs/48.mp3",
  },
  {
    id: "49",
    title: "昨夜书",
    album: "近期单曲",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/49.mp3",
  },
  {
    id: "50",
    title: "留香",
    album: "近期单曲",
    year: 2023,
    rank: null,
    comment: "",
    audioUrl: "/songs/50.mp3",
  },
  {
    id: "51",
    title: "等",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/51.mp3",
  },
  {
    id: "52",
    title: "而或",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/52.mp3",
  },
  {
    id: "53",
    title: "野人",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/53.mp3",
  },
  {
    id: "54",
    title: "雨幕",
    album: "近期单曲",
    year: 2019,
    rank: null,
    comment: "",
    audioUrl: "/songs/54.mp3",
  },
  {
    id: "55",
    title: "忆黄山",
    album: "近期单曲",
    year: 2022,
    rank: null,
    comment: "",
    audioUrl: "/songs/55.mp3",
  },
  {
    id: "56",
    title: "羡慕",
    album: "近期单曲",
    year: 2020,
    rank: null,
    comment: "",
    audioUrl: "/songs/56.mp3",
  },
  {
    id: "57",
    title: "认错",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/57.mp3",
  },
  {
    id: "58",
    title: "内线",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/58.mp3",
  },
  {
    id: "59",
    title: "坏孩子",
    album: "《自定义》",
    year: 2009,
    rank: null,
    comment: "",
    audioUrl: "/songs/59.mp3",
  },
  {
    id: "60",
    title: "宿敌",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/60.mp3",
  },
  // ─── UPGRADING TRACKS 61 TO 128 TO COMPLETE INDIE CHRONICLES ───
  {
    id: "61",
    title: "拆东墙",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/61.mp3",
  },
  {
    id: "62",
    title: "医生",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/62.mp3",
  },
  {
    id: "63",
    title: "毁人不倦",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/63.mp3",
  },
  {
    id: "64",
    title: "河山大好",
    album: "《苏格拉没有底》",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/64.mp3",
  },
  {
    id: "65",
    title: "悄悄话",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/65.mp3",
  },
  {
    id: "66",
    title: "装样",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/66.mp3",
  },
  {
    id: "67",
    title: "伴虎",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/67.mp3",
  },
  {
    id: "68",
    title: "格式化",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/68.mp3",
  },
  {
    id: "69",
    title: "亲情式的爱情",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/69.mp3",
  },
  {
    id: "70",
    title: "玩火",
    album: "《梦游计》",
    year: 2012,
    rank: null,
    comment: "",
    audioUrl: "/songs/70.mp3",
  },
  {
    id: "71",
    title: "违章动物",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/71.mp3",
  },
  {
    id: "72",
    title: "隐形书签",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/72.mp3",
  },
  {
    id: "73",
    title: "宇宙之大",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/73.mp3",
  },
  {
    id: "74",
    title: "梧桐雨",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/74.mp3",
  },
  {
    id: "75",
    title: "奇谈",
    album: "《不如吃茶去》",
    year: 2014,
    rank: null,
    comment: "",
    audioUrl: "/songs/75.mp3",
  },
  {
    id: "76",
    title: "幻胖",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/76.mp3",
  },
  {
    id: "77",
    title: "燕归巢",
    album: "单曲",
    year: 2015,
    rank: null,
    comment: "",
    audioUrl: "/songs/77.mp3",
  },
  {
    id: "78",
    title: "摆脱",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/78.mp3",
  },
  {
    id: "79",
    title: "早介",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/79.mp3",
  },
  {
    id: "80",
    title: "姑娘",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/80.mp3",
  },
  {
    id: "81",
    title: "样",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/81.mp3",
  },
  {
    id: "82",
    title: "暖童话",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/82.mp3",
  },
  {
    id: "83",
    title: "诗书二十一",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/83.mp3",
  },
  {
    id: "84",
    title: "柳成荫",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/84.mp3",
  },
  {
    id: "85",
    title: "假如宽恕",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/85.mp3",
  },
  {
    id: "86",
    title: "撒花",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/86.mp3",
  },
  {
    id: "87",
    title: "七夕",
    album: "单曲",
    year: 2011,
    rank: null,
    comment: "",
    audioUrl: "/songs/87.mp3",
  },
  {
    id: "88",
    title: "庞贝",
    album: "《呼吸之野》",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/88.mp3",
  },
  {
    id: "89",
    title: "蜀雨流芳",
    album: "近期单曲",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/89.mp3",
  },
  {
    id: "90",
    title: "羁绊",
    album: "近期单曲",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/90.mp3",
  },
  {
    id: "91",
    title: "浪沙淘尽",
    album: "近期单曲",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/91.mp3",
  },
  {
    id: "92",
    title: "照夜镜",
    album: "近期单曲",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/92.mp3",
  },
  {
    id: "93",
    title: "金蝉脱壳",
    album: "近期单曲",
    year: 2021,
    rank: null,
    comment: "",
    audioUrl: "/songs/93.mp3",
  },
  {
    id: "94",
    title: "标本",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/94.mp3",
  },
  {
    id: "95",
    title: "绝代风华",
    album: "单曲",
    year: 2017,
    rank: null,
    comment: "",
    audioUrl: "/songs/95.mp3",
  },
  {
    id: "96",
    title: "纯真",
    album: "单曲",
    year: 2013,
    rank: null,
    comment: "",
    audioUrl: "/songs/96.mp3",
  },
  {
    id: "97",
    title: "天龙八部之天下第一",
    album: "单曲",
    year: 2013,
    rank: null,
    comment: "",
    audioUrl: "/songs/97.mp3",
  },
  {
    id: "98",
    title: "放肆",
    album: "单曲",
    year: 2019,
    rank: null,
    comment: "",
    audioUrl: "/songs/98.mp3",
  },
  {
    id: "99",
    title: "绝代双骄",
    album: "近期单曲",
    year: 2020,
    rank: null,
    comment: "",
    audioUrl: "/songs/99.mp3",
  },
  {
    id: "100",
    title: "安徒生不后悔",
    album: "早期单曲",
    year: 2007,
    rank: null,
    comment: "",
    audioUrl: "/songs/100.mp3",
  },
  {
    id: "101",
    title: "我们的恋爱画板",
    album: "早期单曲",
    year: 2007,
    rank: null,
    comment: "",
    audioUrl: "/songs/101.mp3",
  },
  {
    id: "102",
    title: "摇头玩",
    album: "早期单曲",
    year: 2007,
    rank: null,
    comment: "",
    audioUrl: "/songs/102.mp3",
  },
  {
    id: "103",
    title: "墨尔本，晴",
    album: "早期单曲",
    year: 2007,
    rank: null,
    comment: "",
    audioUrl: "/songs/103.mp3",
  },
  {
    id: "104",
    title: "唯爱雨",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/104.mp3",
  },
  {
    id: "105",
    title: "尘世美",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/105.mp3",
  },
  {
    id: "106",
    title: "惟爱你",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/106.mp3",
  },
  {
    id: "107",
    title: "散场恋歌",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/107.mp3",
  },
  {
    id: "108",
    title: "我无所谓",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/108.mp3",
  },
  {
    id: "109",
    title: "爱情里的眼泪",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/109.mp3",
  },
  {
    id: "110",
    title: "飞吹沙",
    album: "早期单曲",
    year: 2007,
    rank: null,
    comment: "",
    audioUrl: "/songs/110.mp3",
  },
  {
    id: "111",
    title: "愚人节的歌",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/111.mp3",
  },
  {
    id: "112",
    title: "送你的小说",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/112.mp3",
  },
  {
    id: "113",
    title: "七号公园",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/113.mp3",
  },
  {
    id: "114",
    title: "特别",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/114.mp3",
  },
  {
    id: "115",
    title: "静态电影",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/115.mp3",
  },
  {
    id: "116",
    title: "凉亭",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/116.mp3",
  },
  {
    id: "117",
    title: "碎碎念",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/117.mp3",
  },
  {
    id: "118",
    title: "伤声",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/118.mp3",
  },
  {
    id: "119",
    title: "飞得更高",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/119.mp3",
  },
  {
    id: "120",
    title: "梦溪笔谈",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/120.mp3",
  },
  {
    id: "121",
    title: "两种悲伤",
    album: "早期单曲",
    year: 2008,
    rank: null,
    comment: "",
    audioUrl: "/songs/121.mp3",
  },
  {
    id: "122",
    title: "梧桐灯",
    album: "《青年晚报》",
    year: 2016,
    rank: null,
    comment: "",
    audioUrl: "/songs/122.mp3",
  },
  {
    id: "123",
    title: "千古",
    album: "单曲",
    year: 2015,
    rank: null,
    comment: "",
    audioUrl: "/songs/123.mp3",
  },
  {
    id: "124",
    title: "九月清晨",
    album: "《寻宝游戏》",
    year: 2018,
    rank: null,
    comment: "",
    audioUrl: "/songs/124.mp3",
  },
  {
    id: "125",
    title: "我想牵着你的手",
    album: "早期单曲",
    year: 2006,
    rank: null,
    comment: "",
    audioUrl: "/songs/125.mp3",
  },
  {
    id: "126",
    title: "有钱有闲",
    album: "近期单曲",
    year: 2020,
    rank: null,
    comment: "",
    audioUrl: "/songs/126.mp3",
  },
  {
    id: "127",
    title: "大不自多",
    album: "近期单曲",
    year: 2022,
    rank: null,
    comment: "",
    audioUrl: "/songs/127.mp3",
  },
  {
    id: "128",
    title: "新天龙八部之战歌",
    album: "近期单曲",
    year: 2023,
    rank: null,
    comment: "",
    audioUrl: "/songs/128.mp3",
  },
];
