// Generated by scripts/generate-openapi-client.mjs. Do not edit manually.

export interface OpenApiComponents {
  schemas: {
    AssignRoleRequest: { roleIds: Array<number> };
    ApiResponseVoid: { code?: number; message?: string; data?: unknown; traceId?: string };
    UserProfileRequest: {
      nickname?: string;
      avatar?: string;
      bio?: string;
      location?: string;
      website?: string;
      email?: string;
    };
    PasswordChangeRequest: { currentPassword: string; newPassword: string };
    ReadingProgressRequest: { progressPercent: number; positionAnchor?: string };
    ApiResponseReadingHistoryResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["ReadingHistoryResponse"];
      traceId?: string;
    };
    CategoryResponse: {
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
      icon?: string;
      createdAt?: string;
    };
    PostDigestResponse: {
      id?: number;
      title?: string;
      slug?: string;
      coverImage?: string;
      summary?: string;
      authorName?: string;
      authorAvatar?: string;
      category?: OpenApiComponents["schemas"]["CategoryResponse"];
      views?: number;
      likesCount?: number;
      publishedAt?: string;
    };
    ReadingHistoryResponse: {
      post?: OpenApiComponents["schemas"]["PostDigestResponse"];
      progressPercent?: number;
      positionAnchor?: string;
      lastReadAt?: string;
      completedAt?: string;
    };
    PostCollectionRequest: { name: string; description?: string };
    ApiResponsePostCollectionResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PostCollectionResponse"];
      traceId?: string;
    };
    PostCollectionResponse: {
      id?: number;
      name?: string;
      description?: string;
      itemCount?: number;
      createdAt?: string;
      updatedAt?: string;
    };
    CommentUpdateRequest: { content: string };
    WebhookRequest: {
      name: string;
      url: string;
      secret: string;
      events: Array<"POST_PUBLISHED" | "POST_ARCHIVED" | "POST_DELETED" | "COMMENT_SUBMITTED">;
      isActive: boolean;
    };
    ApiResponseWebhookResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["WebhookResponse"];
      traceId?: string;
    };
    WebhookResponse: {
      id?: number;
      name?: string;
      url?: string;
      events?: Array<"POST_PUBLISHED" | "POST_ARCHIVED" | "POST_DELETED" | "COMMENT_SUBMITTED">;
      isActive?: boolean;
      createdAt?: string;
    };
    TagRequest: { name: string; slug: string };
    ApiResponseTagResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["TagResponse"];
      traceId?: string;
    };
    TagResponse: { id?: number; name?: string; slug?: string; createdAt?: string };
    SeriesRequest: {
      name: string;
      slug: string;
      description?: string;
      coverImage?: string;
      isPublished?: boolean;
    };
    ApiResponseSeriesResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["SeriesResponse"];
      traceId?: string;
    };
    Breadcrumb: { id?: number; title?: string; slug?: string };
    Navigation: {
      prev?: OpenApiComponents["schemas"]["Neighbor"];
      next?: OpenApiComponents["schemas"]["Neighbor"];
    };
    Neighbor: { title?: string; slug?: string };
    PostResponse: {
      id?: number;
      title?: string;
      slug?: string;
      coverImage?: string;
      summary?: string;
      autoSummary?: string;
      content?: string;
      contentType?: "JSON" | "MDX";
      status?: "DRAFT" | "PENDING_REVIEW" | "SCHEDULED" | "PUBLISHED" | "REJECTED" | "ARCHIVED";
      reviewComment?: string;
      reviewerName?: string;
      reviewedAt?: string;
      publishedAt?: string;
      scheduledAt?: string;
      archiveReason?: string;
      archivedAt?: string;
      archivedByName?: string;
      isFeatured?: boolean;
      views?: number;
      likesCount?: number;
      favoritesCount?: number;
      wordCount?: number;
      readingTimeMinutes?: number;
      contentHash?: string;
      toc?: string;
      isLiked?: boolean;
      isFavorited?: boolean;
      authorName?: string;
      authorAvatar?: string;
      category?: OpenApiComponents["schemas"]["CategoryResponse"];
      series?: OpenApiComponents["schemas"]["SeriesResponse"];
      seriesOrder?: number;
      parentId?: number;
      path?: string;
      tags?: Array<OpenApiComponents["schemas"]["TagResponse"]>;
      createdAt?: string;
      updatedAt?: string;
      breadcrumbs?: Array<OpenApiComponents["schemas"]["Breadcrumb"]>;
      seo?: OpenApiComponents["schemas"]["SeoMetadata"];
      navigation?: OpenApiComponents["schemas"]["Navigation"];
    };
    SeoMetadata: {
      ogTitle?: string;
      ogDescription?: string;
      ogImage?: string;
      ogType?: string;
      ogUrl?: string;
      twitterCard?: string;
      canonicalUrl?: string;
    };
    SeriesResponse: {
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
      coverImage?: string;
      isPublished?: boolean;
      postsCount?: number;
      posts?: Array<OpenApiComponents["schemas"]["PostResponse"]>;
      createdAt?: string;
    };
    RoleRequest: { name: string; code: string; description?: string };
    ApiResponseRoleResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["RoleResponse"];
      traceId?: string;
    };
    RoleResponse: { id?: number; name?: string; code?: string; description?: string };
    ProjectRequest: {
      name: string;
      slug: string;
      description?: string;
      coverImage?: string;
      githubUrl?: string;
      previewUrl?: string;
      techStack?: string;
      sortOrder?: number;
      isPublished: boolean;
    };
    ApiResponseProjectResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["ProjectResponse"];
      traceId?: string;
    };
    ProjectResponse: {
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
      coverImage?: string;
      githubUrl?: string;
      previewUrl?: string;
      techStack?: string;
      starsCount?: number;
      forksCount?: number;
      language?: string;
      sortOrder?: number;
      isPublished?: boolean;
      createdAt?: string;
    };
    PostRequest: {
      title: string;
      slug?: string;
      coverImage?: string;
      summary?: string;
      content: string;
      contentType?: "JSON" | "MDX";
      status: "DRAFT" | "PENDING_REVIEW" | "SCHEDULED" | "PUBLISHED" | "REJECTED" | "ARCHIVED";
      isFeatured?: boolean;
      categoryId?: number;
      seriesId?: number;
      seriesOrder?: number;
      parentId?: number;
      tagIds?: Array<number>;
    };
    ApiResponsePostResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PostResponse"];
      traceId?: string;
    };
    MomentRequest: {
      content: string;
      isPublished: boolean;
      images?: Array<OpenApiComponents["schemas"]["MomentImageRequest"]>;
    };
    MomentImageRequest: { fileId: number; altText: string };
    ApiResponseMomentResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["MomentResponse"];
      traceId?: string;
    };
    MomentResponse: {
      id?: number;
      content?: string;
      likesCount?: number;
      isPublished?: boolean;
      createdAt?: string;
      updatedAt?: string;
      images?: Array<OpenApiComponents["schemas"]["MomentImageResponse"]>;
    };
    MomentImageResponse: {
      id?: number;
      fileId?: number;
      originalName?: string;
      fileUrl?: string;
      thumbnailUrl?: string;
      width?: number;
      height?: number;
      altText?: string;
      sortOrder?: number;
    };
    MenuRequest: {
      name: string;
      parentId: number;
      path?: string;
      permission?: string;
      type: number;
      icon?: string;
      sortOrder?: number;
      isVisible?: boolean;
      isPublic?: boolean;
    };
    ApiResponseMenuResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["MenuResponse"];
      traceId?: string;
    };
    MenuResponse: {
      id?: number;
      parentId?: number;
      name?: string;
      path?: string;
      permission?: string;
      type?: number;
      icon?: string;
      sortOrder?: number;
      isVisible?: boolean;
      isPublic?: boolean;
      createdAt?: string;
      children?: Array<OpenApiComponents["schemas"]["MenuResponse"]>;
    };
    KanbanItemRequest: {
      title: string;
      content?: string;
      priority: "LOW" | "MEDIUM" | "HIGH";
      columnId: number;
      orderIndex?: number;
      reminderAt?: string;
      tagIds?: Array<number>;
    };
    ApiResponseKanbanItemResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["KanbanItemResponse"];
      traceId?: string;
    };
    KanbanItemResponse: {
      id?: number;
      title?: string;
      content?: string;
      priority?: "LOW" | "MEDIUM" | "HIGH";
      orderIndex?: number;
      columnId?: number;
      reminderAt?: string;
      tags?: Array<OpenApiComponents["schemas"]["TagResponse"]>;
      createdAt?: string;
      updatedAt?: string;
    };
    KanbanColumnRequest: { name: string; color?: string; orderIndex?: number };
    ApiResponseKanbanColumnResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["KanbanColumnResponse"];
      traceId?: string;
    };
    KanbanColumnResponse: {
      id?: number;
      name?: string;
      color?: string;
      orderIndex?: number;
      items?: Array<OpenApiComponents["schemas"]["KanbanItemResponse"]>;
      createdAt?: string;
      updatedAt?: string;
    };
    FriendLinkRequest: {
      name: string;
      url: string;
      avatar?: string;
      description?: string;
      email?: string;
      sortOrder?: number;
      isPublished?: boolean;
      status?: "APPLYING" | "APPROVED" | "REJECTED";
    };
    ApiResponseFriendLinkResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["FriendLinkResponse"];
      traceId?: string;
    };
    FriendLinkResponse: {
      id?: number;
      name?: string;
      url?: string;
      avatar?: string;
      description?: string;
      email?: string;
      status?: "APPLYING" | "APPROVED" | "REJECTED";
      sortOrder?: number;
      isPublished?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    ConfigRequest: {
      configKey: string;
      configValue?: string;
      configName: string;
      description?: string;
      isPublic: boolean;
    };
    ApiResponseConfigResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["ConfigResponse"];
      traceId?: string;
    };
    ConfigResponse: {
      id?: number;
      configKey?: string;
      configValue?: string;
      configName?: string;
      description?: string;
      isPublic?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    CategoryRequest: { name: string; slug: string; description?: string; icon?: string };
    ApiResponseCategoryResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["CategoryResponse"];
      traceId?: string;
    };
    GuestbookRequest: { content: string; parentId?: number };
    FriendLinkApplicationRequest: {
      name: string;
      url: string;
      avatar?: string;
      description?: string;
      email: string;
    };
    CommentRequest: { content: string; postId: number; parentId?: number };
    CommentReportRequest: { reason: string; description?: string };
    RegisterRequest: { username: string; email: string; password: string };
    ApiResponse: { code?: number; message?: string; data?: unknown; traceId?: string };
    ApiResponseAuthResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["AuthResponse"];
      traceId?: string;
    };
    AuthResponse: {
      accessToken?: string;
      refreshToken?: string;
      tokenType?: string;
      username?: string;
      email?: string;
      roles?: Array<string>;
    };
    OtpSendRequest: { email: string };
    OtpLoginRequest: { email: string; code: string };
    LoginRequest: { username: string; password: string };
    AssignMenuRequest: { menuIds: Array<number> };
    PostScheduleRequest: { scheduledAt: string };
    PostReviewRequest: { approved: boolean; reviewComment?: string };
    ApiResponseString: { code?: number; message?: string; data?: string; traceId?: string };
    PostArchiveRequest: { reason: string };
    ApiResponseInteger: { code?: number; message?: string; data?: number; traceId?: string };
    PostAutosaveRequest: { identifier: string; content: unknown; contentType?: "JSON" | "MDX" };
    KanbanItemMoveRequest: { itemId: number; targetColumnId: number; targetOrderIndex: number };
    ApiResponseFileResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["FileResponse"];
      traceId?: string;
    };
    FileResponse: {
      id?: number;
      fileName?: string;
      originalName?: string;
      fileUrl?: string;
      thumbnailUrl?: string;
      width?: number;
      height?: number;
      fileSize?: number;
      fileType?: string;
      createdAt?: string;
    };
    BatchModerateCommentRequest: {
      ids: Array<number>;
      status: "PENDING" | "APPROVED" | "REJECTED" | "SPAM";
    };
    Pageable: { page?: number; size?: number; sort?: Array<string> };
    ApiResponsePageResultNotificationResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultNotificationResponse"];
      traceId?: string;
    };
    NotificationResponse: {
      id?: number;
      title?: string;
      content?: string;
      type?: string;
      read?: boolean;
      readAt?: string;
      link?: string;
      createdAt?: string;
    };
    PageResultNotificationResponse: {
      list?: Array<OpenApiComponents["schemas"]["NotificationResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseLong: { code?: number; message?: string; data?: number; traceId?: string };
    ApiResponseUserInfoResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["UserInfoResponse"];
      traceId?: string;
    };
    UserInfoResponse: {
      id?: number;
      username?: string;
      nickname?: string;
      avatar?: string;
      roles?: Array<string>;
      permissions?: Array<string>;
    };
    ApiResponseContentPreferenceResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["ContentPreferenceResponse"];
      traceId?: string;
    };
    ContentPreferenceResponse: {
      followedCategories?: Array<OpenApiComponents["schemas"]["CategoryResponse"]>;
      hiddenPostCount?: number;
    };
    ApiResponsePersonalLibraryOverviewResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PersonalLibraryOverviewResponse"];
      traceId?: string;
    };
    FavoritePostResponse: {
      post?: OpenApiComponents["schemas"]["PostDigestResponse"];
      favoritedAt?: string;
    };
    PersonalLibraryOverviewResponse: {
      continueReading?: Array<OpenApiComponents["schemas"]["ReadingHistoryResponse"]>;
      recentFavorites?: Array<OpenApiComponents["schemas"]["FavoritePostResponse"]>;
      recommendations?: Array<OpenApiComponents["schemas"]["RecommendedPostResponse"]>;
    };
    RecommendedPostResponse: {
      post?: OpenApiComponents["schemas"]["PostDigestResponse"];
      reasonCode?: string;
      reason?: string;
    };
    ApiResponsePageResultReadingHistoryResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultReadingHistoryResponse"];
      traceId?: string;
    };
    PageResultReadingHistoryResponse: {
      list?: Array<OpenApiComponents["schemas"]["ReadingHistoryResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponsePageResultPostDigestResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultPostDigestResponse"];
      traceId?: string;
    };
    PageResultPostDigestResponse: {
      list?: Array<OpenApiComponents["schemas"]["PostDigestResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponsePageResultFavoritePostResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultFavoritePostResponse"];
      traceId?: string;
    };
    PageResultFavoritePostResponse: {
      list?: Array<OpenApiComponents["schemas"]["FavoritePostResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseListPostCollectionResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["PostCollectionResponse"]>;
      traceId?: string;
    };
    ApiResponsePageResultCollectionPostResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultCollectionPostResponse"];
      traceId?: string;
    };
    CollectionPostResponse: {
      post?: OpenApiComponents["schemas"]["PostDigestResponse"];
      addedAt?: string;
    };
    PageResultCollectionPostResponse: {
      list?: Array<OpenApiComponents["schemas"]["CollectionPostResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponsePageResultCommentResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultCommentResponse"];
      traceId?: string;
    };
    CommentResponse: {
      id?: number;
      parentId?: number;
      content?: string;
      username?: string;
      nickname?: string;
      avatar?: string;
      status?: "PENDING" | "APPROVED" | "REJECTED" | "SPAM";
      postId?: number;
      postTitle?: string;
      likesCount?: number;
      reportsCount?: number;
      replyCount?: number;
      likedByCurrentUser?: boolean;
      pinned?: boolean;
      featured?: boolean;
      deletedPlaceholder?: boolean;
      createdAt?: string;
      editedAt?: string;
    };
    PageResultCommentResponse: {
      list?: Array<OpenApiComponents["schemas"]["CommentResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseListTagResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["TagResponse"]>;
      traceId?: string;
    };
    ApiResponsePublicStatsResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PublicStatsResponse"];
      traceId?: string;
    };
    PublicStatsResponse: {
      totalPosts?: number;
      totalComments?: number;
      totalViews?: number;
      runtimeDays?: number;
    };
    ApiResponseListPostResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["PostResponse"]>;
      traceId?: string;
    };
    ApiResponseListSeriesResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["SeriesResponse"]>;
      traceId?: string;
    };
    ApiResponseListTreeLong: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["TreeLong"]>;
      traceId?: string;
    };
    TreeLong: {
      name?: { empty?: boolean };
      id?: number;
      weight?: unknown;
      parentId?: number;
      config?: OpenApiComponents["schemas"]["TreeNodeConfig"];
      empty?: boolean;
      [key: string]: unknown;
    };
    TreeNodeConfig: {
      idKey?: string;
      parentIdKey?: string;
      weightKey?: string;
      nameKey?: string;
      childrenKey?: string;
      deep?: number;
    };
    ApiResponseUnifiedSearchResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["UnifiedSearchResponse"];
      traceId?: string;
    };
    SearchGroup: {
      type?: string;
      label?: string;
      priority?: number;
      items?: Array<OpenApiComponents["schemas"]["SearchResultItem"]>;
    };
    SearchResultItem: {
      id?: string;
      title?: string;
      subtitle?: string;
      description?: string;
      url?: string;
      icon?: string;
      iconColor?: string;
      type?: string;
      shortcut?: Array<string>;
      score?: number;
      metadata?: { [key: string]: unknown };
    };
    UnifiedSearchResponse: {
      groups?: Array<OpenApiComponents["schemas"]["SearchGroup"]>;
      totalHits?: number;
      processingTimeMs?: number;
    };
    ApiResponseListString: {
      code?: number;
      message?: string;
      data?: Array<string>;
      traceId?: string;
    };
    ApiResponseQuickSearchResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["QuickSearchResponse"];
      traceId?: string;
    };
    QuickSearchResponse: {
      posts?: Array<OpenApiComponents["schemas"]["SearchResultItem"]>;
      categories?: Array<OpenApiComponents["schemas"]["SearchResultItem"]>;
      tags?: Array<OpenApiComponents["schemas"]["SearchResultItem"]>;
    };
    ApiResponsePageResultPostDocument: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultPostDocument"];
      traceId?: string;
    };
    PageResultPostDocument: {
      list?: Array<OpenApiComponents["schemas"]["PostDocument"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    PostDocument: {
      id?: string;
      title?: string;
      slug?: string;
      summary?: string;
      content?: string;
      authorName?: string;
      categoryName?: string;
      tags?: Array<string>;
      publishedAt?: string;
      views?: number;
    };
    ApiResponseListProjectResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["ProjectResponse"]>;
      traceId?: string;
    };
    ApiResponsePageResultMomentResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultMomentResponse"];
      traceId?: string;
    };
    PageResultMomentResponse: {
      list?: Array<OpenApiComponents["schemas"]["MomentResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseListMarketIndexResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["MarketIndexResponse"]>;
      traceId?: string;
    };
    MarketIndexResponse: {
      name?: string;
      symbol?: string;
      current?: number;
      changePct?: number;
      sparkline?: Array<number>;
      isOpen?: boolean;
    };
    ApiResponseMarketIndexResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["MarketIndexResponse"];
      traceId?: string;
    };
    ApiResponseCursorPageResponseCommentResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["CursorPageResponseCommentResponse"];
      traceId?: string;
    };
    CursorPageResponseCommentResponse: {
      list?: Array<OpenApiComponents["schemas"]["CommentResponse"]>;
      nextCursor?: number;
      hasMore?: boolean;
    };
    ApiResponseGitHubStatsResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["GitHubStatsResponse"];
      traceId?: string;
    };
    GitHubStatsResponse: {
      followers?: number;
      publicRepos?: number;
      totalStars?: number;
      htmlUrl?: string;
      avatarUrl?: string;
    };
    ApiResponseListFriendLinkResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["FriendLinkResponse"]>;
      traceId?: string;
    };
    ApiResponseListConfigResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["ConfigResponse"]>;
      traceId?: string;
    };
    ApiResponseCommentAnchorContextResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["CommentAnchorContextResponse"];
      traceId?: string;
    };
    CommentAnchorContextResponse: {
      rootCommentId?: number;
      rootComment?: OpenApiComponents["schemas"]["CommentResponse"];
      targetComment?: OpenApiComponents["schemas"]["CommentResponse"];
      repliesWindow?: OpenApiComponents["schemas"]["PageResultCommentResponse"];
    };
    ApiResponseListCategoryResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["CategoryResponse"]>;
      traceId?: string;
    };
    ApiResponsePageResultPostResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultPostResponse"];
      traceId?: string;
    };
    PageResultPostResponse: {
      list?: Array<OpenApiComponents["schemas"]["PostResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseListPostDigestResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["PostDigestResponse"]>;
      traceId?: string;
    };
    ApiResponseBlogFacetResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["BlogFacetResponse"];
      traceId?: string;
    };
    ArchiveFacet: { year?: number; month?: number; count?: number };
    BlogFacetResponse: {
      totalPublishedCount?: number;
      categories?: Array<OpenApiComponents["schemas"]["CategoryFacet"]>;
      tags?: Array<OpenApiComponents["schemas"]["TagFacet"]>;
      archives?: Array<OpenApiComponents["schemas"]["ArchiveFacet"]>;
      contentTypes?: Array<OpenApiComponents["schemas"]["ContentTypeFacet"]>;
    };
    CategoryFacet: { id?: number; name?: string; slug?: string; count?: number };
    ContentTypeFacet: { contentType?: "JSON" | "MDX"; count?: number };
    TagFacet: { id?: number; name?: string; slug?: string; count?: number };
    ApiResponseBlogDiscoveryResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["BlogDiscoveryResponse"];
      traceId?: string;
    };
    BlogDiscoveryResponse: {
      spotlight?: OpenApiComponents["schemas"]["PostDigestResponse"];
      curated?: Array<OpenApiComponents["schemas"]["PostDigestResponse"]>;
      latest?: Array<OpenApiComponents["schemas"]["PostDigestResponse"]>;
      mostRead?: Array<OpenApiComponents["schemas"]["PostDigestResponse"]>;
      categoryGroups?: Array<OpenApiComponents["schemas"]["CategoryGroup"]>;
    };
    CategoryGroup: {
      category?: OpenApiComponents["schemas"]["CategoryResponse"];
      heroPost?: OpenApiComponents["schemas"]["PostDigestResponse"];
      supportingPosts?: Array<OpenApiComponents["schemas"]["PostDigestResponse"]>;
      posts?: Array<OpenApiComponents["schemas"]["PostDigestResponse"]>;
      totalPublishedCount?: number;
      latestPublishedAt?: string;
      score?: number;
    };
    ApiResponseListWebhookResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["WebhookResponse"]>;
      traceId?: string;
    };
    ApiResponsePageResultWebhookLog: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultWebhookLog"];
      traceId?: string;
    };
    PageResultWebhookLog: {
      list?: Array<OpenApiComponents["schemas"]["WebhookLog"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    Webhook: {
      id?: number;
      createdBy?: string;
      createdAt?: string;
      lastModifiedBy?: string;
      updatedAt?: string;
      isDeleted?: boolean;
      name?: string;
      url?: string;
      secret?: string;
      events?: string;
      isActive?: boolean;
    };
    WebhookLog: {
      id?: number;
      createdBy?: string;
      createdAt?: string;
      lastModifiedBy?: string;
      updatedAt?: string;
      isDeleted?: boolean;
      deliveryId?: string;
      webhook?: OpenApiComponents["schemas"]["Webhook"];
      event?: string;
      url?: string;
      requestPayload?: string;
      responsePayload?: string;
      responseCode?: number;
      isSuccess?: boolean;
      errorMessage?: string;
      attemptCount?: number;
    };
    ApiResponseListUserResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["UserResponse"]>;
      traceId?: string;
    };
    UserResponse: {
      id?: number;
      username?: string;
      email?: string;
      nickname?: string;
      status?: "ACTIVE" | "INACTIVE" | "PENDING" | "BANNED" | "DELETED";
      createdAt?: string;
      roles?: Array<string>;
    };
    ApiResponseUserResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["UserResponse"];
      traceId?: string;
    };
    ApiResponseListRoleResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["RoleResponse"]>;
      traceId?: string;
    };
    ApiResponseListLong: {
      code?: number;
      message?: string;
      data?: Array<number>;
      traceId?: string;
    };
    ApiResponsePageResultProjectResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultProjectResponse"];
      traceId?: string;
    };
    PageResultProjectResponse: {
      list?: Array<OpenApiComponents["schemas"]["ProjectResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseListPostRevisionResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["PostRevisionResponse"]>;
      traceId?: string;
    };
    PostRevisionResponse: {
      id?: number;
      postId?: number;
      title?: string;
      summary?: string;
      content?: string;
      contentType?: "JSON" | "MDX";
      versionNumber?: number;
      createdBy?: string;
      changeType?: string;
      changeSummary?: string;
      contentHash?: string;
      createdAt?: string;
    };
    ApiResponsePostDiffResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PostDiffResponse"];
      traceId?: string;
    };
    FieldDiff: { original?: string; revised?: string; changed?: boolean; diffHtml?: string };
    PostDiffResponse: {
      title?: OpenApiComponents["schemas"]["FieldDiff"];
      summary?: OpenApiComponents["schemas"]["FieldDiff"];
      content?: OpenApiComponents["schemas"]["FieldDiff"];
    };
    ApiResponsePostAutosaveResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PostAutosaveResponse"];
      traceId?: string;
    };
    PostAutosaveResponse: { content?: unknown; contentType?: "JSON" | "MDX" };
    ApiResponseDict: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["Dict"];
      traceId?: string;
    };
    Dict: { empty?: boolean; [key: string]: unknown };
    ApiResponsePageResultOperationLog: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultOperationLog"];
      traceId?: string;
    };
    OperationLog: {
      id?: number;
      createdBy?: string;
      createdAt?: string;
      lastModifiedBy?: string;
      updatedAt?: string;
      isDeleted?: boolean;
      username?: string;
      description?: string;
      methodName?: string;
      requestMethod?: string;
      requestUrl?: string;
      ipAddress?: string;
      userAgent?: string;
      parameters?: string;
      result?: string;
      duration?: number;
      status?: number;
      errorMessage?: string;
      traceId?: string;
    };
    PageResultOperationLog: {
      list?: Array<OpenApiComponents["schemas"]["OperationLog"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponsePageResultLinkCheckLog: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultLinkCheckLog"];
      traceId?: string;
    };
    LinkCheckLog: {
      id?: number;
      createdBy?: string;
      createdAt?: string;
      lastModifiedBy?: string;
      updatedAt?: string;
      isDeleted?: boolean;
      url?: string;
      sourceType?: string;
      sourceId?: number;
      sourceTitle?: string;
      statusCode?: number;
      isBroken?: boolean;
      errorMessage?: string;
    };
    PageResultLinkCheckLog: {
      list?: Array<OpenApiComponents["schemas"]["LinkCheckLog"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseListKanbanColumnResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["KanbanColumnResponse"]>;
      traceId?: string;
    };
    ApiResponsePageResultFriendLinkResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultFriendLinkResponse"];
      traceId?: string;
    };
    PageResultFriendLinkResponse: {
      list?: Array<OpenApiComponents["schemas"]["FriendLinkResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponsePageResultFileResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultFileResponse"];
      traceId?: string;
    };
    PageResultFileResponse: {
      list?: Array<OpenApiComponents["schemas"]["FileResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseDashboardStatsResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["DashboardStatsResponse"];
      traceId?: string;
    };
    DashboardStatsResponse: {
      totalUsers?: number;
      totalPosts?: number;
      totalComments?: number;
      pendingComments?: number;
      totalViews?: number;
    };
    ApiResponsePageResultCommentReportResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultCommentReportResponse"];
      traceId?: string;
    };
    CommentReportResponse: {
      commentId?: number;
      reporterId?: number;
      reporterUsername?: string;
      reporterNickname?: string;
      reason?: string;
      description?: string;
      status?: "OPEN" | "ACTIONED" | "DISMISSED";
      handledBy?: string;
      handledAt?: string;
      resolutionNote?: string;
      postId?: number;
      postTitle?: string;
      parentId?: number;
      commentStatus?: "PENDING" | "APPROVED" | "REJECTED" | "SPAM";
      commentContent?: string;
      createdAt?: string;
    };
    PageResultCommentReportResponse: {
      list?: Array<OpenApiComponents["schemas"]["CommentReportResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseCommentGovernanceOverviewResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["CommentGovernanceOverviewResponse"];
      traceId?: string;
    };
    CommentGovernanceOverviewResponse: {
      totalComments?: number;
      pendingComments?: number;
      approvedComments?: number;
      rejectedComments?: number;
      spamComments?: number;
      openReports?: number;
      actionedReports?: number;
      dismissedReports?: number;
      reportsLast24Hours?: number;
      autoFlaggedLast24Hours?: number;
      oldestPendingAt?: string;
      commentsByStatus?: Array<OpenApiComponents["schemas"]["CommentStatusCount"]>;
      reportsByStatus?: Array<OpenApiComponents["schemas"]["ReportStatusCount"]>;
      moderationActionsLast7Days?: Array<OpenApiComponents["schemas"]["ModerationActionCount"]>;
    };
    CommentStatusCount: { status?: "PENDING" | "APPROVED" | "REJECTED" | "SPAM"; count?: number };
    ModerationActionCount: {
      action?: "SUBMITTED" | "EDITED" | "STATUS_CHANGED" | "AUTO_FLAGGED" | "DELETED";
      count?: number;
    };
    ReportStatusCount: { status?: "OPEN" | "ACTIONED" | "DISMISSED"; count?: number };
    ApiResponsePageResultCommentModerationLogResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultCommentModerationLogResponse"];
      traceId?: string;
    };
    CommentModerationLogResponse: {
      id?: number;
      commentId?: number;
      postId?: number;
      postTitle?: string;
      parentId?: number;
      commentContent?: string;
      action?: "SUBMITTED" | "EDITED" | "STATUS_CHANGED" | "AUTO_FLAGGED" | "DELETED";
      previousStatus?: "PENDING" | "APPROVED" | "REJECTED" | "SPAM";
      newStatus?: "PENDING" | "APPROVED" | "REJECTED" | "SPAM";
      moderatorUsername?: string;
      reason?: string;
      batchId?: string;
      note?: string;
      createdAt?: string;
    };
    PageResultCommentModerationLogResponse: {
      list?: Array<OpenApiComponents["schemas"]["CommentModerationLogResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponsePageResultCommentRiskResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["PageResultCommentRiskResponse"];
      traceId?: string;
    };
    CommentRiskResponse: {
      id?: number;
      parentId?: number;
      postId?: number;
      postTitle?: string;
      content?: string;
      username?: string;
      nickname?: string;
      avatar?: string;
      status?: "PENDING" | "APPROVED" | "REJECTED" | "SPAM";
      reportsCount?: number;
      openReports?: number;
      likesCount?: number;
      riskScore?: number;
      createdAt?: string;
      editedAt?: string;
    };
    PageResultCommentRiskResponse: {
      list?: Array<OpenApiComponents["schemas"]["CommentRiskResponse"]>;
      total?: number;
      page?: number;
      size?: number;
      totalPages?: number;
    };
    ApiResponseTrafficStatsResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["TrafficStatsResponse"];
      traceId?: string;
    };
    Metric: { value?: string; numericValue?: number; growthRate?: number };
    SummaryMetrics: {
      sessions?: OpenApiComponents["schemas"]["Metric"];
      users?: OpenApiComponents["schemas"]["Metric"];
      bounceRate?: OpenApiComponents["schemas"]["Metric"];
      avgSession?: OpenApiComponents["schemas"]["Metric"];
    };
    TimeSeriesItem: { date?: string; sessions?: number; users?: number };
    TrafficMetric: { name?: string; views?: number; percentage?: number };
    TrafficStatsResponse: {
      summary?: OpenApiComponents["schemas"]["SummaryMetrics"];
      timeSeries?: Array<OpenApiComponents["schemas"]["TimeSeriesItem"]>;
      devices?: Array<OpenApiComponents["schemas"]["TrafficMetric"]>;
      sources?: Array<OpenApiComponents["schemas"]["TrafficMetric"]>;
    };
    ApiResponseListTopPageResponse: {
      code?: number;
      message?: string;
      data?: Array<OpenApiComponents["schemas"]["TopPageResponse"]>;
      traceId?: string;
    };
    TopPageResponse: {
      path?: string;
      views?: number;
      "avs.time"?: string;
      bounce?: number;
      trend?: string;
    };
    AnalyticsOverviewResponse: {
      todayPv?: number;
      todayUv?: number;
      yesterdayPv?: number;
      yesterdayUv?: number;
      pvGrowthRate?: number;
      dailyTrends?: Array<OpenApiComponents["schemas"]["VisitTrendItem"]>;
      topContent?: Array<OpenApiComponents["schemas"]["TopContentItem"]>;
    };
    ApiResponseAnalyticsOverviewResponse: {
      code?: number;
      message?: string;
      data?: OpenApiComponents["schemas"]["AnalyticsOverviewResponse"];
      traceId?: string;
    };
    TopContentItem: { title?: string; url?: string; count?: number };
    VisitTrendItem: { date?: string; pv?: number; uv?: number };
  };
}
