// Generated by scripts/generate-openapi-client.mjs. Do not edit manually.

import { baseApi, transformApiError } from "@/lib/api";
import { notifyMutation } from "@/lib/toast";
import type { OpenApiComponents } from "./openapi.generated";

type OpenApiData<T> = T extends { data?: infer D } ? NonNullable<D> : unknown;

export const openapiApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    assignRoles: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number; body: OpenApiComponents["schemas"]["AssignRoleRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/users/${arg.id}/roles`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    getMyPreferences: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseNotificationPreferenceResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/user/notifications/preferences` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    updateMyPreferences: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseNotificationPreferenceResponse"]>,
      { body: OpenApiComponents["schemas"]["NotificationPreferenceRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/user/notifications/preferences`,
        method: "PUT",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    updateWebhook: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseWebhookResponse"]>,
      { id: number; body: OpenApiComponents["schemas"]["WebhookRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/webhooks/${arg.id}`, method: "PUT", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    deleteWebhook: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/webhooks/${arg.id}`, method: "DELETE" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    enableUser: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/users/${arg.id}/enable`, method: "PUT" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    disableUser: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/users/${arg.id}/disable`, method: "PUT" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    retrieveSeries: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseSeriesResponse"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/series/${arg.id}` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    updateSeries: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseSeriesResponse"]>,
      { id: number; body: OpenApiComponents["schemas"]["SeriesRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/series/${arg.id}`, method: "PUT", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    deleteSeries: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/series/${arg.id}`, method: "DELETE" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    updateChecklistItem: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanChecklistItemResponse"]>,
      {
        taskId: number;
        checklistItemId: number;
        body: OpenApiComponents["schemas"]["KanbanChecklistItemRequest"];
      }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/tasks/${arg.taskId}/checklist/${arg.checklistItemId}`,
        method: "PUT",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    deleteChecklistItem: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { taskId: number; checklistItemId: number }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/tasks/${arg.taskId}/checklist/${arg.checklistItemId}`,
        method: "DELETE",
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    updateTask: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanItemResponse"]>,
      { id: number; body: OpenApiComponents["schemas"]["KanbanItemRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/tasks/${arg.id}`,
        method: "PUT",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    deleteTask: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/kanban/tasks/${arg.id}`, method: "DELETE" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    assignTaskAssignees: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanItemResponse"]>,
      { id: number; body: OpenApiComponents["schemas"]["KanbanTaskAssigneeRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/tasks/${arg.id}/assignees`,
        method: "PUT",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    updateColumn: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanColumnResponse"]>,
      { id: number; body: OpenApiComponents["schemas"]["KanbanColumnRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/columns/${arg.id}`,
        method: "PUT",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    deleteColumn: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/kanban/columns/${arg.id}`, method: "DELETE" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    updateConfig: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseConfigResponse"]>,
      { id: number; body: OpenApiComponents["schemas"]["ConfigRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/configs/${arg.id}`, method: "PUT", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    deleteConfig: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/configs/${arg.id}`, method: "DELETE" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    getColumn: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseSeriesResponse"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/columns/${arg.id}` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    subscribe: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { email: string }
    >({
      query: (arg) => ({
        url: `/api/v1/public/newsletter/subscribe`,
        method: "POST",
        params: { email: arg.email },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    unfavoritePost: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePostInteractionResponse"]>,
      { postId: number }
    >({
      query: (arg) => ({
        url: `/api/v1/public/interactions/posts/${arg.postId}/unfavorite`,
        method: "POST",
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    reportPost: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number; body: OpenApiComponents["schemas"]["PostReportRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/public/blog/posts/${arg.id}/report`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    requestPasswordReset: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { body: OpenApiComponents["schemas"]["PasswordResetRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/auth/password/reset/request`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    confirmPasswordReset: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { body: OpenApiComponents["schemas"]["PasswordResetConfirmRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/auth/password/reset/confirm`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    listWebhooks: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListWebhookResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/webhooks` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    createWebhook: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseWebhookResponse"]>,
      { body: OpenApiComponents["schemas"]["WebhookRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/webhooks`, method: "POST", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    testWebhook: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/webhooks/${arg.id}/test`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    redeliverWebhookLog: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { deliveryId: string }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/webhooks/logs/${arg.deliveryId}/redeliver`,
        method: "POST",
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    auditUser: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number; approved: boolean }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/users/${arg.id}/audit`,
        method: "POST",
        params: { approved: arg.approved },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    retrieveAllSeries: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListSeriesResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/series` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    createSeries: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseSeriesResponse"]>,
      { body: OpenApiComponents["schemas"]["SeriesRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/series`, method: "POST", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    rebuildIndex: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/search/rebuild`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    deletePosts: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { body: OpenApiComponents["schemas"]["BatchDeleteRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts`, method: "DELETE", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    withdrawFromReview: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts/${arg.id}/withdraw`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    submitForReview: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts/${arg.id}/submit`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    schedulePost: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number; body: OpenApiComponents["schemas"]["PostScheduleRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/posts/${arg.id}/schedule`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    cancelScheduledPost: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts/${arg.id}/schedule`, method: "DELETE" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    reviewPost: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number; body: OpenApiComponents["schemas"]["PostReviewRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/posts/${arg.id}/review`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    restoreArchivedPost: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts/${arg.id}/restore`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    createPreviewToken: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseString"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts/${arg.id}/preview-token`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    copyPost: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePostResponse"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts/${arg.id}/copy`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    archivePost: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number; body: OpenApiComponents["schemas"]["PostArchiveRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/posts/${arg.id}/archive`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    regenerateStaticHtml: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/posts/regenerate-static`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    rebuildPostMetadata: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseInteger"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/posts/rebuild-metadata`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    triggerManualScan: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/links/scan`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    createTask: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanItemResponse"]>,
      { body: OpenApiComponents["schemas"]["KanbanItemRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/kanban/tasks`, method: "POST", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    retrieveChecklistItems: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListKanbanChecklistItemResponse"]>,
      { taskId: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/kanban/tasks/${arg.taskId}/checklist` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    createChecklistItem: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanChecklistItemResponse"]>,
      { taskId: number; body: OpenApiComponents["schemas"]["KanbanChecklistItemRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/tasks/${arg.taskId}/checklist`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    adjustChecklistItemSequence: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { taskId: number; body: Array<number> }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/tasks/${arg.taskId}/checklist/sequence`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    duplicateTask: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanItemResponse"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/kanban/tasks/${arg.id}/duplicate`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    relocateTask: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { body: OpenApiComponents["schemas"]["KanbanItemMoveRequest"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/tasks/relocate`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    createColumn: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanColumnResponse"]>,
      { body: OpenApiComponents["schemas"]["KanbanColumnRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/kanban/columns`, method: "POST", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    adjustColumnSequence: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { body: Array<number> }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/columns/sequence`,
        method: "POST",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    triggerSync: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/github/sync`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    getAllConfigs: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListConfigResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/configs` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    createConfig: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseConfigResponse"]>,
      { body: OpenApiComponents["schemas"]["ConfigRequest"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/configs`, method: "POST", body: arg.body }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    repairCommentCounters: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseInteger"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/comments/repair-counters`, method: "POST" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    resolvePostReport: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      {
        postId: number;
        reporterId: number;
        body: OpenApiComponents["schemas"]["PostReportResolutionRequest"];
      }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/posts/reports/${arg.postId}/${arg.reporterId}`,
        method: "PATCH",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    completeChecklistItem: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseKanbanChecklistItemResponse"]>,
      {
        taskId: number;
        checklistItemId: number;
        body: OpenApiComponents["schemas"]["KanbanChecklistItemCompletionRequest"];
      }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/kanban/tasks/${arg.taskId}/checklist/${arg.checklistItemId}/completion`,
        method: "PATCH",
        body: arg.body,
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    pinComment: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number; pinned: boolean }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/comments/${arg.id}/pin`,
        method: "PATCH",
        params: { pinned: arg.pinned },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    featureComment: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number; featured: boolean }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/comments/${arg.id}/feature`,
        method: "PATCH",
        params: { featured: arg.featured },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    getLikedPosts: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultLikedPostResponse"]>,
      { pageable: OpenApiComponents["schemas"]["Pageable"] }
    >({
      query: (arg) => ({ url: `/api/v1/user/library/likes`, params: { pageable: arg.pageable } }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getPublicStatistics: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePublicStatsResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/public/stats` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getTrending: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListPostResponse"]>,
      { limit?: number }
    >({
      query: (arg) => ({ url: `/api/v1/public/stats/trending`, params: { limit: arg.limit } }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrievePublicSeries: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListSeriesResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/public/series` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveSeriesWithPosts: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseSeriesResponse"]>,
      { slug: string }
    >({
      query: (arg) => ({ url: `/api/v1/public/series/${arg.slug}` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveSeriesTree: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListTreeLong"]>,
      { slug: string }
    >({
      query: (arg) => ({ url: `/api/v1/public/series/${arg.slug}/tree` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveSitemap: builder.query<string, void>({
      query: () => ({ url: `/api/v1/public/seo/sitemap.xml` }),

      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveRobotsTxt: builder.query<string, void>({
      query: () => ({ url: `/api/v1/public/seo/robots.txt` }),

      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveRssFeed: builder.query<string, void>({
      query: () => ({ url: `/api/v1/public/seo/feed.xml` }),

      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getSuggestions: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListString"]>,
      { keyword: string }
    >({
      query: (arg) => ({
        url: `/api/v1/public/search/suggestions`,
        params: { keyword: arg.keyword },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    quickSearch: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseQuickSearchResponse"]>,
      { keyword: string }
    >({
      query: (arg) => ({ url: `/api/v1/public/search/quick`, params: { keyword: arg.keyword } }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    verify: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { token: string }
    >({
      query: (arg) => ({ url: `/api/v1/public/newsletter/verify`, params: { token: arg.token } }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    unsubscribe: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { token: string }
    >({
      query: (arg) => ({
        url: `/api/v1/public/newsletter/unsubscribe`,
        params: { token: arg.token },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveStats: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseGitHubStatsResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/public/github/stats` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getPublicConfigs: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListConfigResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/public/configs` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getConfigByKey: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseConfigResponse"]>,
      { key: string }
    >({
      query: (arg) => ({ url: `/api/v1/public/configs/${arg.key}` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrievePreview: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePostResponse"]>,
      { token: string }
    >({
      query: (arg) => ({ url: `/api/v1/public/blog/preview/${arg.token}` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    searchPostDigests: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultPostDigestResponse"]>,
      {
        categoryId?: number;
        tagId?: number;
        keyword?: string;
        featuredOnly?: boolean;
        hasCover?: boolean;
        contentType?: "JSON" | "MDX";
        pageable: OpenApiComponents["schemas"]["Pageable"];
      }
    >({
      query: (arg) => ({
        url: `/api/v1/public/blog/posts/digest`,
        params: {
          categoryId: arg.categoryId,
          tagId: arg.tagId,
          keyword: arg.keyword,
          featuredOnly: arg.featuredOnly,
          hasCover: arg.hasCover,
          contentType: arg.contentType,
          pageable: arg.pageable,
        },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveFacets: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseBlogFacetResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/public/blog/facets` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveDiscovery: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseBlogDiscoveryResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/public/blog/discovery` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveArchive: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultPostDigestResponse"]>,
      { year?: number; month?: number; pageable: OpenApiComponents["schemas"]["Pageable"] }
    >({
      query: (arg) => ({
        url: `/api/v1/public/blog/archive`,
        params: { year: arg.year, month: arg.month, pageable: arg.pageable },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getWebhookLogs: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultWebhookLog"]>,
      { id: number; pageable: OpenApiComponents["schemas"]["Pageable"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/webhooks/${arg.id}/logs`,
        params: { pageable: arg.pageable },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getUserById: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseUserResponse"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/users/${arg.id}` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    deleteUser: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/users/${arg.id}`, method: "DELETE" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),

    retrieveRevision: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePostRevisionDetailResponse"]>,
      { id: number; revisionId: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts/${arg.id}/revisions/${arg.revisionId}` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveRevisionSummaries: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListPostRevisionSummaryResponse"]>,
      { id: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/posts/${arg.id}/revisions/summary` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    compareRevisions: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePostDiffResponse"]>,
      { id: number; baseId: number; targetId: number }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/posts/${arg.id}/revisions/compare`,
        params: { baseId: arg.baseId, targetId: arg.targetId },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getPostReports: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultPostReportResponse"]>,
      {
        status?: "OPEN" | "ACTIONED" | "DISMISSED";
        postId?: number;
        reporterUsername?: string;
        pageable: OpenApiComponents["schemas"]["Pageable"];
      }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/posts/reports`,
        params: {
          status: arg.status,
          postId: arg.postId,
          reporterUsername: arg.reporterUsername,
          pageable: arg.pageable,
        },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getSystemSnapshot: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseDict"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/observability/snapshot` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getLogs: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultOperationLog"]>,
      {
        username?: string;
        operation?: string;
        status?: number;
        pageable: OpenApiComponents["schemas"]["Pageable"];
      }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/logs`,
        params: {
          username: arg.username,
          operation: arg.operation,
          status: arg.status,
          pageable: arg.pageable,
        },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getBrokenLinks: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultLinkCheckLog"]>,
      { pageable: OpenApiComponents["schemas"]["Pageable"] }
    >({
      query: (arg) => ({ url: `/api/v1/admin/links/broken`, params: { pageable: arg.pageable } }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    retrieveBoard: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListKanbanColumnResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/kanban` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getStorageInventory: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseStorageInventoryResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/files/inventory` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    verifyStorageIntegrity: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseStorageIntegrityResponse"]>,
      { pageable: OpenApiComponents["schemas"]["Pageable"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/files/integrity`,
        params: { pageable: arg.pageable },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getCommentReports: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultCommentReportResponse"]>,
      {
        status?: "OPEN" | "ACTIONED" | "DISMISSED";
        commentId?: number;
        reporterUsername?: string;
        pageable: OpenApiComponents["schemas"]["Pageable"];
      }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/comments/reports`,
        params: {
          status: arg.status,
          commentId: arg.commentId,
          reporterUsername: arg.reporterUsername,
          pageable: arg.pageable,
        },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getCommentGovernanceOverview: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseCommentGovernanceOverviewResponse"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/comments/overview` }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getCommentModerationLogs: builder.query<
      OpenApiData<
        OpenApiComponents["schemas"]["ApiResponsePageResultCommentModerationLogResponse"]
      >,
      {
        commentId?: number;
        action?: "SUBMITTED" | "EDITED" | "STATUS_CHANGED" | "AUTO_FLAGGED" | "DELETED";
        pageable: OpenApiComponents["schemas"]["Pageable"];
      }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/comments/moderation-logs`,
        params: { commentId: arg.commentId, action: arg.action, pageable: arg.pageable },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getHighRiskComments: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponsePageResultCommentRiskResponse"]>,
      { minOpenReports?: number; pageable: OpenApiComponents["schemas"]["Pageable"] }
    >({
      query: (arg) => ({
        url: `/api/v1/admin/comments/high-risk`,
        params: { minOpenReports: arg.minOpenReports, pageable: arg.pageable },
      }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    getTrending1: builder.query<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseListPostResponse"]>,
      { limit?: number }
    >({
      query: (arg) => ({ url: `/api/v1/admin/analytics/trending`, params: { limit: arg.limit } }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,

      providesTags: ["OpenApi"],
    }),

    clearLogs: builder.mutation<OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>, void>(
      {
        query: () => ({ url: `/api/v1/admin/logs/clear`, method: "DELETE" }),
        transformResponse: (response: { data: unknown }) => response.data as never,
        transformErrorResponse: transformApiError,
        async onQueryStarted(_arg, { queryFulfilled }) {
          await notifyMutation(queryFulfilled, { error: "Request failed." });
        },
        invalidatesTags: ["OpenApi"],
      }
    ),

    clearLogs1: builder.mutation<
      OpenApiData<OpenApiComponents["schemas"]["ApiResponseVoid"]>,
      void
    >({
      query: () => ({ url: `/api/v1/admin/links/logs`, method: "DELETE" }),
      transformResponse: (response: { data: unknown }) => response.data as never,
      transformErrorResponse: transformApiError,
      async onQueryStarted(_arg, { queryFulfilled }) {
        await notifyMutation(queryFulfilled, { error: "Request failed." });
      },
      invalidatesTags: ["OpenApi"],
    }),
  }),
  overrideExisting: false,
});

export const {
  useAssignRolesMutation,
  useGetMyPreferencesQuery,
  useUpdateMyPreferencesMutation,
  useUpdateWebhookMutation,
  useDeleteWebhookMutation,
  useEnableUserMutation,
  useDisableUserMutation,
  useRetrieveSeriesQuery,
  useUpdateSeriesMutation,
  useDeleteSeriesMutation,
  useUpdateChecklistItemMutation,
  useDeleteChecklistItemMutation,
  useUpdateTaskMutation,
  useDeleteTaskMutation,
  useAssignTaskAssigneesMutation,
  useUpdateColumnMutation,
  useDeleteColumnMutation,
  useUpdateConfigMutation,
  useDeleteConfigMutation,
  useGetColumnQuery,
  useSubscribeMutation,
  useUnfavoritePostMutation,
  useReportPostMutation,
  useRequestPasswordResetMutation,
  useConfirmPasswordResetMutation,
  useListWebhooksQuery,
  useCreateWebhookMutation,
  useTestWebhookMutation,
  useRedeliverWebhookLogMutation,
  useAuditUserMutation,
  useRetrieveAllSeriesQuery,
  useCreateSeriesMutation,
  useRebuildIndexMutation,
  useDeletePostsMutation,
  useWithdrawFromReviewMutation,
  useSubmitForReviewMutation,
  useSchedulePostMutation,
  useCancelScheduledPostMutation,
  useReviewPostMutation,
  useRestoreArchivedPostMutation,
  useCreatePreviewTokenMutation,
  useCopyPostMutation,
  useArchivePostMutation,
  useRegenerateStaticHtmlMutation,
  useRebuildPostMetadataMutation,
  useTriggerManualScanMutation,
  useCreateTaskMutation,
  useRetrieveChecklistItemsQuery,
  useCreateChecklistItemMutation,
  useAdjustChecklistItemSequenceMutation,
  useDuplicateTaskMutation,
  useRelocateTaskMutation,
  useCreateColumnMutation,
  useAdjustColumnSequenceMutation,
  useTriggerSyncMutation,
  useGetAllConfigsQuery,
  useCreateConfigMutation,
  useRepairCommentCountersMutation,
  useResolvePostReportMutation,
  useCompleteChecklistItemMutation,
  usePinCommentMutation,
  useFeatureCommentMutation,
  useGetLikedPostsQuery,
  useGetPublicStatisticsQuery,
  useGetTrendingQuery,
  useRetrievePublicSeriesQuery,
  useRetrieveSeriesWithPostsQuery,
  useRetrieveSeriesTreeQuery,
  useRetrieveSitemapQuery,
  useRetrieveRobotsTxtQuery,
  useRetrieveRssFeedQuery,
  useGetSuggestionsQuery,
  useQuickSearchQuery,
  useVerifyQuery,
  useUnsubscribeQuery,
  useRetrieveStatsQuery,
  useGetPublicConfigsQuery,
  useGetConfigByKeyQuery,
  useRetrievePreviewQuery,
  useSearchPostDigestsQuery,
  useRetrieveFacetsQuery,
  useRetrieveDiscoveryQuery,
  useRetrieveArchiveQuery,
  useGetWebhookLogsQuery,
  useGetUserByIdQuery,
  useDeleteUserMutation,
  useRetrieveRevisionQuery,
  useRetrieveRevisionSummariesQuery,
  useCompareRevisionsQuery,
  useGetPostReportsQuery,
  useGetSystemSnapshotQuery,
  useGetLogsQuery,
  useGetBrokenLinksQuery,
  useRetrieveBoardQuery,
  useGetStorageInventoryQuery,
  useVerifyStorageIntegrityQuery,
  useGetCommentReportsQuery,
  useGetCommentGovernanceOverviewQuery,
  useGetCommentModerationLogsQuery,
  useGetHighRiskCommentsQuery,
  useGetTrending1Query,
  useClearLogsMutation,
  useClearLogs1Mutation,
} = openapiApi;
