import { ClockIcon, FileTextIcon, GearIcon, PersonsIcon, SparklesIcon } from "@/components/icons";
import { createActionCommand, createNavigationCommand } from "./command-model";
import { CommandIntent, type CommandItem } from "./types";

export const STATIC_COMMANDS: readonly CommandItem[] = [
  // AI category
  createActionCommand({
    id: "smart-summarize-week",
    title: "Summarize this week's progress",
    description: "AI-generated summary of your activities",
    icon: SparklesIcon,
    category: "AI",
    source: "ai",
    order: 1,
    keywords: ["weekly progress", "summary", "本周进展", "总结"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("AI: Summarize week"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "smart-create-task",
    title: "Create a task for the team",
    description: "Use AI to draft and assign tasks",
    icon: SparklesIcon,
    category: "AI",
    source: "ai",
    order: 2,
    keywords: ["task", "todo", "assign", "团队任务"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("AI: Create task"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "smart-draft-brief",
    title: "Draft a project brief",
    description: "AI-assisted project documentation",
    icon: SparklesIcon,
    category: "AI",
    source: "ai",
    order: 3,
    keywords: ["brief", "spec", "outline", "项目简介"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("AI: Draft brief"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "smart-schedule-standup",
    title: "Schedule a standup meeting",
    description: "Find a time and invite members",
    icon: SparklesIcon,
    category: "AI",
    source: "ai",
    order: 4,
    keywords: ["meeting", "sync", "standup", "会议", "站会"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("AI: Schedule standup"), closeOnExecute: true },
    defaultVisible: true,
  }),

  // Management category
  createActionCommand({
    id: "result-view-activity",
    title: "View recent activity",
    description: "See what's happening across your projects",
    icon: ClockIcon,
    category: "Management",
    source: "system",
    order: 10,
    keywords: ["activity", "history", "updates", "最近活动"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("System: View activity"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "result-project-roadmap",
    title: "Open project roadmap",
    description: "Visualize goals and milestones",
    icon: FileTextIcon,
    category: "Management",
    source: "system",
    order: 11,
    keywords: ["roadmap", "plan", "timeline", "路线图"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("System: Open roadmap"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "result-team-directory",
    title: "Browse team directory",
    description: "Connect with your coworkers",
    icon: PersonsIcon,
    category: "Management",
    source: "system",
    order: 12,
    keywords: ["people", "members", "coworkers", "团队成员"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("System: Browse team"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "result-workspace-settings",
    title: "Manage workspace settings",
    description: "Configure your collaborative environment",
    icon: GearIcon,
    category: "Management",
    source: "system",
    order: 13,
    keywords: ["preferences", "config", "设置", "工作区"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/" },
    defaultVisible: true,
  }),
];
