import {
  ArchiveIcon,
  ArrowRightFromSquareIcon,
  ClockIcon,
  FileTextIcon,
  GearIcon,
  PersonsIcon,
  SparklesIcon,
} from "@/components/icons";
import { createActionCommand, createNavigationCommand } from "./command-model";
import { CommandIntent, type CommandItem } from "./types";

export const STATIC_COMMANDS: readonly CommandItem[] = [
  createNavigationCommand({
    id: "navigate-explore-writing",
    title: "Explore writing",
    description: "Browse articles by topic and tag",
    icon: ArchiveIcon,
    category: "System",
    source: "navigation",
    order: 0,
    keywords: ["explore", "archive", "topics", "tags", "writing", "discover"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/explore" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-projects",
    title: "Browse projects",
    description: "Explore tools, experiments, and open-source work",
    icon: FileTextIcon,
    category: "System",
    source: "navigation",
    order: 1,
    keywords: ["projects", "portfolio", "tools", "experiments", "open source", "builds"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/projects" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-links",
    title: "Visit the blogroll",
    description: "Browse friends and places worth reading",
    icon: ArrowRightFromSquareIcon,
    category: "System",
    source: "navigation",
    order: 2,
    keywords: ["links", "blogroll", "friends", "web", "exchange", "travelogue"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/links" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-guestbook",
    title: "Sign the guestbook",
    description: "Read notes from visitors and leave your own",
    icon: FileTextIcon,
    category: "System",
    source: "navigation",
    order: 3,
    keywords: ["guestbook", "comments", "notes", "message", "sign", "visitor log"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/guestbook" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-uses",
    title: "Browse equipment & setup",
    description: "Explore the physical hardware, tools, and workspace staples",
    icon: GearIcon,
    category: "System",
    source: "navigation",
    order: 4,
    keywords: [
      "uses",
      "equipment",
      "setup",
      "hardware",
      "software",
      "workspace",
      "tools",
      "macbook",
      "staples",
    ],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/uses" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-about",
    title: "Read about Odyssey",
    description: "Learn about the genesis, pillars, and story behind Odyssey",
    icon: FileTextIcon,
    category: "System",
    source: "navigation",
    order: 5,
    keywords: ["about", "genesis", "story", "pillars", "philosophy", "profile", "bio"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/about" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-roadmap",
    title: "View Odyssey Roadmap",
    description: "Explore the chronological milestones, shipped architectures, and future goals",
    icon: ClockIcon,
    category: "System",
    source: "navigation",
    order: 6,
    keywords: ["roadmap", "changelog", "progress", "milestones", "evolution", "versions"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/roadmap" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-schedule",
    title: "Manage Focus Schedule",
    description: "Launch the interactive scheduler to plan work and block focused intervals",
    icon: ClockIcon,
    category: "System",
    source: "navigation",
    order: 7,
    keywords: ["schedule", "agenda", "focus", "planner", "calendar", "time", "tasks", "blocking"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/schedule" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-explorer",
    title: "Browse Codebase Map",
    description: "Launch the interactive repository explorer to trace files and system layers",
    icon: GearIcon,
    category: "System",
    source: "navigation",
    order: 8,
    keywords: [
      "explorer",
      "codebase",
      "workspace",
      "files",
      "tree",
      "repository",
      "map",
      "structure",
    ],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/explorer" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-gallery",
    title: "Browse Photo Portfolio",
    description: "Launch the medium-format photography gallery to view landscapes and geometry",
    icon: ArchiveIcon,
    category: "System",
    source: "navigation",
    order: 9,
    keywords: [
      "gallery",
      "photos",
      "photography",
      "analog",
      "hasselblad",
      "film",
      "portfolio",
      "landscapes",
    ],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/gallery" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-tour",
    title: "Take Workspace Tour",
    description: "Launch the interactive stepper guide to trace systems, design, and physical rigs",
    icon: PersonsIcon,
    category: "System",
    source: "navigation",
    order: 10,
    keywords: [
      "tour",
      "onboarding",
      "guide",
      "stepper",
      "welcome",
      "introduction",
      "walkthrough",
      "journey",
    ],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/tour" },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "navigate-recruiter",
    title: "Evaluate Recruiter Sandbox",
    description:
      "Tailor-fit applicant evaluation panel to calculate match scores and filter achievements",
    icon: PersonsIcon,
    category: "System",
    source: "navigation",
    order: 11,
    keywords: [
      "recruiter",
      "hiring",
      "resume",
      "evaluation",
      "sandbox",
      "match",
      "fit",
      "assessment",
      "cv",
      "portfolio",
    ],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/recruiter" },
    defaultVisible: true,
  }),

  // AI category
  createNavigationCommand({
    id: "navigate-copilot",
    title: "Chat with Odyssey Copilot",
    description:
      "Launch the AI Assistant to explore the site, bio details, and system configurations",
    icon: SparklesIcon,
    category: "AI",
    source: "navigation",
    order: 0,
    keywords: ["copilot", "ai", "chat", "assistant", "ask", "bot", "guide", "helper"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/copilot" },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "smart-summarize-week",
    title: "Summarize this week's progress",
    description: "AI-generated summary of your activities",
    icon: SparklesIcon,
    category: "AI",
    source: "ai",
    order: 1,
    keywords: ["weekly progress", "summary", "weekly", "progress report"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("AI: Summarize week"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "smart-create-task",
    title: "Create a task for the team",
    description: "Use AI to draft and assign tasks",
    icon: SparklesIcon,
    category: "AI",
    source: "ai",
    order: 2,
    keywords: ["task", "todo", "assign", "team task"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("AI: Create task"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "smart-draft-brief",
    title: "Draft a project brief",
    description: "AI-assisted project documentation",
    icon: SparklesIcon,
    category: "AI",
    source: "ai",
    order: 3,
    keywords: ["brief", "spec", "outline", "project brief"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("AI: Draft brief"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "smart-schedule-standup",
    title: "Schedule a standup meeting",
    description: "Find a time and invite members",
    icon: SparklesIcon,
    category: "AI",
    source: "ai",
    order: 4,
    keywords: ["meeting", "sync", "standup", "schedule", "daily sync"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("AI: Schedule standup"), closeOnExecute: true },
    defaultVisible: true,
  }),

  // Management category
  createActionCommand({
    id: "result-view-activity",
    title: "View recent activity",
    description: "See what's happening across your projects",
    icon: ClockIcon,
    category: "Management",
    source: "system",
    order: 10,
    keywords: ["activity", "history", "updates", "recent activity"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("System: View activity"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "result-project-roadmap",
    title: "Open project roadmap",
    description: "Visualize goals and milestones",
    icon: FileTextIcon,
    category: "Management",
    source: "system",
    order: 11,
    keywords: ["roadmap", "plan", "timeline", "roadmap view"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("System: Open roadmap"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createActionCommand({
    id: "result-team-directory",
    title: "Browse team directory",
    description: "Connect with your coworkers",
    icon: PersonsIcon,
    category: "Management",
    source: "system",
    order: 12,
    keywords: ["people", "members", "coworkers", "team members"],
    intent: CommandIntent.EXECUTE,
    payload: { action: () => console.log("System: Browse team"), closeOnExecute: true },
    defaultVisible: true,
  }),
  createNavigationCommand({
    id: "result-workspace-settings",
    title: "Manage workspace settings",
    description: "Configure your collaborative environment",
    icon: GearIcon,
    category: "Management",
    source: "system",
    order: 13,
    keywords: ["preferences", "config", "settings", "workspace"],
    intent: CommandIntent.NAVIGATE,
    payload: { href: "/" },
    defaultVisible: true,
  }),
];
