name: "PR Title Lint"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Lint Pull Request Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Standard Conventional Commit types
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Require scope to be lowercase, but keep it optional (e.g., "feat(blog):" or "feat:")
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: "The subject of the PR title must not start with an uppercase letter to match conventional commits styling."
